### ISSUE TITLE
Ansible vs systemd bug

### ISSUE THREAD

**Issue by Slugger70** [gvlproject/gvl.ansible.image#3]
Ansible is having a problem when run on boot. (The gvl brew commandline system needs an ansible script to run on boot to make some connections including a bind mount between `/home/linuxbrew` and `/mnt/gvl/apps/linuxbrew`..) The ansible script/playbook is stored in `/mnt/gvl/apps/scripts/system-ansible.yml`.. It is called from the `copy_modules` script in `/mnt/galaxy/gvl/poststart.d`

The ansible script is getting an error because systemd will not expand the `~` in paths. Therefore, ansible goes looking for a file that doesn't exist during it's setup phase. This is described in https://github.com/ansible/ansible/issues/20332

Numerous workarounds have been discussed for this but it keeps happening.. The best way is to set a good `remote_tmp` in the ansible config. I've set a test machine to `/mnt/galaxy/tmp` which then made everything work. Arrggghhhh.... 

Upshot - I will put in a pull request to this repo as we need a new base image. But for now I've included an edit into `ansible.cfg` via the poststart.d scripts which is then baked into the filesystem which I am much more familiar with.

**Comment by nuwang** [comment]
Fixed by Simon in commit: https://github.com/gvlproject/gvl.ansible.image/pull/4/commits/ea4da3c9a22881fec297ba0313ebb9c4398d2ebd
